##Import pandas and read in the banklist.csv file into a dataframe called banks.

In [ ]:
import pandas as pd

In [ ]:
p=pd.read_csv('banklist.csv')

In [ ]:
p

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Fayette County Bank,Saint Elmo,IL,1802,"United Fidelity Bank, fsb",26-May-17,26-Jul-17
1,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,WI,30003,First-Citizens Bank & Trust Company,5-May-17,26-Jul-17
2,First NBC Bank,New Orleans,LA,58302,Whitney Bank,28-Apr-17,26-Jul-17
3,Proficio Bank,Cottonwood Heights,UT,35495,Cache Valley Bank,3-Mar-17,18-May-17
4,Seaway Bank and Trust Company,Chicago,IL,19328,State Bank of Texas,27-Jan-17,18-May-17
...,...,...,...,...,...,...,...
548,"Superior Bank, FSB",Hinsdale,IL,32646,"Superior Federal, FSB",27-Jul-01,19-Aug-14
549,Malta National Bank,Malta,OH,6629,North Valley Bank,3-May-01,18-Nov-02
550,First Alliance Bank & Trust Co.,Manchester,NH,34264,Southern New Hampshire Bank & Trust,2-Feb-01,18-Feb-03
551,National State Bank of Metropolis,Metropolis,IL,3815,Banterra Bank of Marion,14-Dec-00,17-Mar-05
552,Bank of Honolulu,Honolulu,HI,21029,Bank of the Orient,13-Oct-00,17-Mar-05

##show the head of the dataframe.

In [ ]:
p.head()

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Fayette County Bank,Saint Elmo,IL,1802,"United Fidelity Bank, fsb",26-May-17,26-Jul-17
1,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,WI,30003,First-Citizens Bank & Trust Company,5-May-17,26-Jul-17
2,First NBC Bank,New Orleans,LA,58302,Whitney Bank,28-Apr-17,26-Jul-17
3,Proficio Bank,Cottonwood Heights,UT,35495,Cache Valley Bank,3-Mar-17,18-May-17
4,Seaway Bank and Trust Company,Chicago,IL,19328,State Bank of Texas,27-Jan-17,18-May-17

In [ ]:
p.head(10)

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Fayette County Bank,Saint Elmo,IL,1802,"United Fidelity Bank, fsb",26-May-17,26-Jul-17
1,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,WI,30003,First-Citizens Bank & Trust Company,5-May-17,26-Jul-17
2,First NBC Bank,New Orleans,LA,58302,Whitney Bank,28-Apr-17,26-Jul-17
3,Proficio Bank,Cottonwood Heights,UT,35495,Cache Valley Bank,3-Mar-17,18-May-17
4,Seaway Bank and Trust Company,Chicago,IL,19328,State Bank of Texas,27-Jan-17,18-May-17
5,Harvest Community Bank,Pennsville,NJ,34951,First-Citizens Bank & Trust Company,13-Jan-17,18-May-17
6,Allied Bank,Mulberry,AR,91,Today's Bank,23-Sep-16,17-Nov-16
7,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,19-Aug-16,1-Jun-17
8,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,6-May-16,6-Sep-16
9,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,29-Apr-16,6-Sep-16

###what are the column names?

In [ ]:
p.columns

Index(['Bank Name', 'City', 'ST', 'CERT', 'Acquiring Institution',
       'Closing Date', 'Updated Date'],
      dtype='object')

##

##how many states (ST) are represented in this data set?

In [ ]:
p['ST'].nunique()

44

In [ ]:
p['ST'].unique()

array(['IL', 'WI', 'LA', 'UT', 'NJ', 'AR', 'GA', 'PA', 'TN', 'WA', 'CO',
       'PR', 'FL', 'MN', 'CA', 'MD', 'OK', 'OH', 'SC', 'VA', 'ID', 'TX',
       'CT', 'AZ', 'NV', 'NC', 'KY', 'MO', 'KS', 'AL', 'MI', 'IN', 'IA',
       'NE', 'MS', 'NM', 'OR', 'NY', 'MA', 'SD', 'WY', 'WV', 'NH', 'HI'],
      dtype=object)

In [ ]:
p.value_counts()

Bank Name                             City          ST  CERT   Acquiring Institution                Closing Date  Updated Date
1st American State Bank of Minnesota  Hancock       MN  15448  Community Development Bank, FSB      5-Feb-10      1-Nov-13        1
Old Harbor Bank                       Clearwater    FL  57537  1st United Bank                      21-Oct-11     21-Mar-14       1
North Milwaukee State Bank            Milwaukee     WI  20364  First-Citizens Bank & Trust Company  11-Mar-16     13-Mar-17       1
Northern Star Bank                    Mankato       MN  34983  BankVista                            19-Dec-14     6-Jan-16        1
Northwest Bank & Trust                Acworth       GA  57658  State Bank and Trust Company         30-Jul-10     21-Sep-15       1
                                                                                                                                 ..
First Banking Center                  Burlington    WI  5287   First Michigan Bank                  19-Nov-10     20-Aug-12       1
First BankAmericano                   Elizabeth     NJ  34270  Crown Bank                           31-Jul-09     20-Aug-12       1
First Bank of Kansas City             Kansas City   MO  25231  Great American Bank                  4-Sep-09      21-Aug-12       1
First Bank of Jacksonville            Jacksonville  FL  27573  Ameris Bank                          22-Oct-10     21-Mar-14       1
ebank                                 Atlanta       GA  34682  Stearns Bank, N.A.                   21-Aug-09     21-Aug-12       1
Name: count, Length: 553, dtype: int64

In [ ]:
p=p.squeeze()

In [ ]:
p

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Fayette County Bank,Saint Elmo,IL,1802,"United Fidelity Bank, fsb",26-May-17,26-Jul-17
1,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,WI,30003,First-Citizens Bank & Trust Company,5-May-17,26-Jul-17
2,First NBC Bank,New Orleans,LA,58302,Whitney Bank,28-Apr-17,26-Jul-17
3,Proficio Bank,Cottonwood Heights,UT,35495,Cache Valley Bank,3-Mar-17,18-May-17
4,Seaway Bank and Trust Company,Chicago,IL,19328,State Bank of Texas,27-Jan-17,18-May-17
...,...,...,...,...,...,...,...
548,"Superior Bank, FSB",Hinsdale,IL,32646,"Superior Federal, FSB",27-Jul-01,19-Aug-14
549,Malta National Bank,Malta,OH,6629,North Valley Bank,3-May-01,18-Nov-02
550,First Alliance Bank & Trust Co.,Manchester,NH,34264,Southern New Hampshire Bank & Trust,2-Feb-01,18-Feb-03
551,National State Bank of Metropolis,Metropolis,IL,3815,Banterra Bank of Marion,14-Dec-00,17-Mar-05
552,Bank of Honolulu,Honolulu,HI,21029,Bank of the Orient,13-Oct-00,17-Mar-05

In [ ]:
p.sample(5)

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
349,"Marshall Bank, N.A.",Hallock,MN,16133,United Valley Bank,29-Jan-10,23-Aug-12
173,Nexity Bank,Birmingham,AL,19794,AloStar Bank of Commerce,15-Apr-11,21-Mar-14
187,Badger State Bank,Cassville,WI,13272,Royal Bank,11-Feb-11,12-Sep-12
344,Marco Community Bank,Marco Island,FL,57586,Mutual of Omaha Bank,19-Feb-10,20-Jul-17
248,Imperial Savings and Loan Association,Martinsville,VA,31623,"River Community Bank, N.A.",20-Aug-10,24-Aug-12